# Generated by Django 2.1.8 on 2019-05-22 14:34

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0002_sitepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
