# Generated by Django 2.1.8 on 2019-05-21 02:26

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_sitepagerich'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepagerich',
            name='body',
            field=wagtail.core.fields.StreamField([('person', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.TextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())]))]),
        ),
    ]
