# Generated by Django 2.1.8 on 2019-05-21 13:36

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190521_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepagerich',
            name='body',
            field=wagtail.core.fields.StreamField([('person', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.TextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.core.blocks.RichTextBlock()), ('contact', wagtail.core.blocks.StreamBlock([]))])))]),
        ),
    ]
